endereco/urls.py
from django.urls import path
from .views import AddressCreate, AddressList, AddressUpdate

app_name = 'endereco'

urlpatterns= [
    path('criar/', AddressCreate.as_view(), name='criar'),
    path('listar/', AddressList.as_view() ,name='list'),
    path('editar/<int:pk>', AddressUpdate.as_view(), name='atualizar')
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('endereco/', include('endereco.urls'), name='endereco'),
]

endereco/models.py
from django.db import models

class Address(models.Model):
    cep = models.CharField(max_length=9)
    logradouro = models.CharField(max_length=50) #rua
    bairro = models.CharField(max_length=30)
    localidade = models.CharField(max_length=30) #cidade
    uf = models.CharField(max_length=2) #estado
    
    

endereco/forms.py
from django import forms
from .models import Address

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        
        fields=['cep', 'logradouro', 'bairro', 'localidade', 'uf']
        
        label={
            'cep': 'CEP',
            'logradouro': 'Rua',
            'bairro': 'Bairro',
            'localidade': 'Cidade',
            'uf': 'UF',
        }
        widgets={
            'cep': forms.TextInput(attrs={'class': 'form-control'}),
            'logradouro': forms.TextInput(attrs={'class': 'form-control'}),
            'bairro': forms.TextInput(attrs={'class': 'form-control'}),
            'localidade': forms.TextInput(attrs={'class': 'form-control'}),
            'uf': forms.TextInput(attrs={'class': 'form-control'}),
        }

endereco/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, UpdateView
from .models import Address
from .forms import AddressForm
from django.urls import reverse_lazy
 
class AddressCreate(CreateView):
    model = Address
    form_class = AddressForm
    context_object_name = 'CreateAddressForm' #nome q o front vai acessar o formulario
    template_name = 'addressForm.html'
    success_url = reverse_lazy('endereco:list') #redericiona quando completar o formulario
    
class AddressList(ListView):
    model = Address
    template_name = 'addressList.html'
    context_object_name = 'addresses'
    
class AddressUpdate(UpdateView):
    model = Address
    form_class = AddressForm
    context_object_name = 'address'
    template_name = 'addressForm.html'
    success_url = reverse_lazy('endereco:list') 

endereco/templates/addressForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario</title>
</head>
<body>
    {% if address %}
        <h1>Editar</h1>
        <form action="{% url 'endereco:atualizar' address.id %}">{% csrf_token %}
            {% for field in form %}
            {{  field.label_tag }}
            <br>
            {{ field }}
            <br>
        {% endfor %}
        <button type="submit">Atualizar</button>
        </form>
    {% endif %}
    <h1>Cadastrar Endereco</h1>
    <form action="{% url 'endereco:criar' %}" method="POST">{% csrf_token %}

        {% for field in form %}
            {{  field.label_tag }}
            <br>
            {{ field }}
            <br>
        {% endfor %}
        <button type="submit">Cadastrar</button>
    </form>


</body>
</html>

endereco/templates/addressList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if addresses %}
        <h1>Endereços</h1>
        <table>
            <tr>
                <th>CEP</th>
                <th>Cidade</th>
                <th>UF</th>
            </tr>
            {% for address in addresses %}
                <tr>
                    <td>{{ address.cep }}</th>
                    <td>{{ address.localidade }}</th>
                    <td>{{ address.uf }}</th>
                </tr>
                {% endfor %}
        </table>
        {% endif %}
</body>
</html>